-- 코드를 입력하세요
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
FROM ANIMAL_INS 
JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE SUBSTRING(ANIMAL_INS.SEX_UPON_INTAKE,1,6) = 'Intact' AND 
      SUBSTRING(ANIMAL_OUTS.SEX_UPON_OUTCOME,1,6) != 'Intact'
ORDER BY ANIMAL_INS.ANIMAL_ID;